-- ============================================
-- 乐淘点菜系统 - 数据库表结构
-- 在 Supabase SQL Editor 中执行此脚本
-- ============================================

-- 分类表
CREATE TABLE categories (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  sort_order INT DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 菜品表
CREATE TABLE dishes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  category_id BIGINT REFERENCES categories(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  price DECIMAL(10,2) NOT NULL,
  image_url TEXT,
  description TEXT,
  is_available BOOLEAN DEFAULT true,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 订单表
CREATE TABLE orders (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  table_number TEXT,
  note TEXT,
  status TEXT DEFAULT 'pending',
  total_price DECIMAL(10,2) NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 订单项表
CREATE TABLE order_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id BIGINT REFERENCES orders(id) ON DELETE CASCADE,
  dish_id BIGINT REFERENCES dishes(id),
  dish_name TEXT NOT NULL,
  quantity INT NOT NULL,
  price DECIMAL(10,2) NOT NULL
);

-- 管理员配置表
CREATE TABLE settings (
  key TEXT PRIMARY KEY,
  value TEXT NOT NULL
);

-- 插入默认管理员密码
INSERT INTO settings (key, value) VALUES ('admin_password', 'admin123');

-- 插入示例数据
INSERT INTO categories (name, sort_order) VALUES
  ('热菜', 1),
  ('凉菜', 2),
  ('主食', 3),
  ('饮品', 4);

INSERT INTO dishes (category_id, name, price, description, is_available) VALUES
  (1, '鱼香肉丝', 28.00, '经典川菜，酸甜微辣', true),
  (1, '宫保鸡丁', 32.00, '花生与鸡丁的绝妙搭配', true),
  (1, '麻婆豆腐', 18.00, '麻辣鲜香', true),
  (2, '凉拌黄瓜', 12.00, '清爽可口', true),
  (2, '口水鸡', 22.00, '红油鲜香', true),
  (3, '蛋炒饭', 15.00, '粒粒分明', true),
  (3, '牛肉面', 22.00, '汤浓面劲', true),
  (4, '可乐', 5.00, '', true),
  (4, '雪碧', 5.00, '', true),
  (4, '王老吉', 8.00, '', true);

-- 开启图片存储的 RLS
-- 需要在 Supabase Dashboard -> Storage 中创建 dish-images 桶
-- 设置公开访问
